In [1]:
import numpy as np

In [2]:
X = np.random.normal(loc = 1, scale = 10, size = (1000,50))

In [3]:
mX = np.mean(X, axis = 0)
sX = np.std(X, axis = 0)
Xnorme = (X - mX)/sX

In [4]:
Z = np.array([[4, 5, 0], 
             [1, 9, 3],              
             [5, 1, 1],
             [3, 3, 3], 
             [9, 9, 9], 
             [4, 7, 1]])

In [5]:
r = np.sum(Z , axis = 1)

In [7]:
print(np.nonzero(r > 10))

(array([1, 4, 5]),)


In [8]:
r

array([ 9, 13,  7,  9, 27, 12])

In [11]:
A = np.eye(3)
B = np.eye(3)

ab = np.vstack((A,B))
ab

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])